# Generated by Django 3.0.3 on 2020-03-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationslot',
            name='available_slot',
            field=models.IntegerField(default=8),
        ),
    ]
